[workspace]
resolver = "3"
members = [
    "api", 
    "database",
    "middlewares",
    "models",
    "repositories",
    "utils", 
    "custom_macros/procedural/derive_columns_and_placeholders", 
    "cli_testing", "types",
]
