[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
tokio = { version = "1.47.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["derive", "macros", "runtime-tokio", "tls-native-tls", "migrate", "postgres"] }
