[package]
name = "models"
version = "0.1.0"
edition = "2024"

[dependencies]
custom_macros = { path = "../custom_macros" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
type_reflect = "0.6.2"
uuid = { version = "1.17.0", features = ["serde"] }
